### ISSUE TITLE
staticImageField question

### ISSUE THREAD

**Issue by geoplin** [amigold/FunDapter#21]
I have a question. I was looking to add an image from my res/drawable folder and not from url so i found this method addStaticImageField() but i dont know how to use it and there is no documentation or example on how it is used properly. Anything i could've missed?

**Comment by ghost** [comment]
@geoplin 

It's basically a free-style field. You implement the StaticImageLoader interface as defined [here](https://github.com/amigold/FunDapter/blob/fb33241f265901d73276608689077d4310278eaf/library/src/com/ami/fundapter/interfaces/StaticImageLoader.java). It accepts the item, ImageView and position and you can set whatever drawable you like on that ImageView.

Its that abstract because I wanted it to have maximum flexibility so you can set whatever logic you want.

Let me know if that helps

**Comment by geoplin** [comment]
Tyvm for the quick reply and yes I've seen the posted link I'm just unsure what "item" is supposed to be

**Comment by ghost** [comment]
Oh, Item is the type from the BindDictionary you are using
so if you do `BindDictionary<Product> dict = new BindDictionary<Product>()`

then the item will be of type `Product`

**Comment by geoplin** [comment]
```
    dict.addStaticImageField(R.id.ivTrafficLight, new StaticImageLoader() {
        @Override
        public void loadImage(Object item, ImageView imageView, int position) {
            imageView.setImageResource(R.drawable.traffic_green);
        }
    });
```

This is how I understand it should work, but obviously I'm wrong as it does not, so could you give me an example. Sorry I'm kinda new to android so things aren't obvious to me.

**Comment by ghost** [comment]
Looks correct. Could you please share more details as to what isn't working?

**Comment by geoplin** [comment]
Ok so here's what I'm trying to achieve: I want to make a ListView that has a TextView and a ImageView. I'm trying to turn this ImageView into a "traffic light" with 3 states. A green, yellow and red. I have the images of these "traffic lights" and I want to change them using google cloud messaging and I have that part working. All I need now is to be able to set the resource of the ImageView in java not xml (like I did with the TextView using StringExtractor) since the source of the ImageView varies in different lines. The above code didn't work, it just gave me empty ImageViews.
